### ISSUE TITLE
comm/all shows messages when it should show little or none

### ISSUE THREAD

**Issue by jbreazeale** [IITC-CE/ingress-intel-total-conversion#417] opened 2020-12-22 23:59 UTC
Here are the steps to reproduce the issue.  Pick a busy area such as San Francisco.  Go to COMM/All.  See that COMM/All has lots of log entries.  Move the map view way off shore.  Notice that COMM/All has nothing in it but messages just to you if any.  Move the map view back to San Francisco and see that COMM/All has lots of log entries as expected.  Now choose COMM/Faction.  In San Francisco there are lots of log entries.  Move the map view way off shore.  Notice the log entries haven't changed, they are just the same as before.  Now choose COMM/All.  Notice you have very few if any log entries.  Now choose COMM/Faction.  Notice there are few if any log entries.

I expected that if one chooses COMM/Faction in a busy area then the map view changes to someplace where there is no activity then COMM/Faction logging would change accordingly, to little or none.

**Comment by johnd0e** [comment] 2020-12-23 08:48
@jbreazeale might be related : https://github.com/le-jeu/ingress-intel-total-conversion/commit/23d0ad8094bd79c1e96ef722a5cd366fc936194b

**Comment by johnd0e** [comment] 2021-03-11 19:28
@le-jeu ?

**Comment by le-jeu** [comment] 2021-03-11 19:43
still reproducible

**Comment by le-jeu** [comment] 2021-03-11 19:49
comm tab is not rendered when there is no data (even if the storehash is reset), common with public&alert
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/2daad393c75f45e9f121136c4717d4dec51fca4f/core/code/chat.js#L182-L191

**Comment by johnd0e** [comment] 2021-03-11 19:49
Have you covered this case in your PR?

**Comment by le-jeu** [comment] 2021-03-11 19:50
I don't

**Comment by johnd0e** [comment] 2021-03-11 19:51
Ok. Will you? Or it is not clear yet how to fix it in proper way?

**Comment by le-jeu** [comment] 2021-03-11 19:55
multiple ways to fix it, but #412 or #447 ?

**Comment by johnd0e** [comment] 2021-03-11 19:58
Not sure, and you are definitely more familiar with this part of code.
So you decide which is more appropriate, may be even separate PR.

**Comment by johnd0e** [comment] 2021-03-13 12:05
@jbreazeale 
Please check if the issue is resolved in our test-build.

**Comment by jbreazeale** [comment] 2021-03-13 12:33
I will need some guidance on how to gain access to a test build.

**Comment by MysticJay** [comment] 2021-03-13 13:06
@jbreazeale iitc.app

**Comment by jbreazeale** [comment] 2021-03-13 23:16
It looks to be fixed.

**Closed as completed** 2021-03-15 08:11 UTC
Labels: bug, core
