### ISSUE TITLE
Map freeze (too much recursion) on edges

### ISSUE THREAD

**Issue by McBen** [IITC-CE/ingress-intel-total-conversion#338] opened 2020-02-19 08:39 UTC
when scrolling to (or open) map top/bottom edge iitc freezes.
In fact it doesn't freeze because the call-loop will be terminated by the browser. But things get weired depending on system.

Tested v.0.30.1 w/o plugins on chrome, firefox and mobile.

open: https://intel.ingress.com/?ll=85.051128,45&z=3 and move

call stack:
```
oo much recursion intel:5039:1
    project https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:5039
    latLngToPoint https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:4879
    project https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:7386
    latLngToLayerPoint https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:7408
    _getCenterOffset https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:7911
    _tryAnimatedPan https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:7986
    setView https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:6590
    panTo https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:6702
    setupMap https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:2845
    fire https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:3974
    panBy https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:6712
    _tryAnimatedPan https://intel.ingress.com/intel?log=debug line 26857 > scriptElement:7991
...
```

**Comment by johnd0e** [comment] 2020-02-19 08:41
Duplicate of #177

**Closed as completed by johnd0e** 2020-02-19 08:41 UTC
