### ISSUE TITLE
IITCm for Android: Allow to add  from URL

### ISSUE THREAD

**Issue by AlfonsoML** [IITC-CE/ingress-intel-total-conversion#274] opened 2019-11-10 12:39 UTC
Like IITC Mobile for iOS, allow the users to paste an URL instead of forcing them to download the plugin to their phone and then install it.  
If this feature is added, the plugin should be automatically enabled afterwards.

**Comment by johnd0e** [comment] 2019-11-10 15:34
Duplicate of #207.
But there are already too much unrelated info, so let's keep this one.

Let's see it as sub-task of #257.

**Comment by Suburbanno** [comment] 2023-08-03 16:51
close
done https://github.com/IITC-CE/ingress-intel-total-conversion/pull/627

**Closed as completed** 2023-08-03 16:55 UTC
Labels: help wanted, mobile
