### ISSUE TITLE
IITC-Mobile: option to add external plugins through URL

### ISSUE THREAD

**Issue by Suburbanno** [IITC-CE/ingress-intel-total-conversion#207] opened 2019-06-02 18:07 UTC

**Comment by johnd0e** [comment] 2019-06-02 19:25
In general, you can add external plugin entering URL in any browser, and then select iitc in app chooser.
But it's known that on some systems it does not work as intended.

It's also possible to manually put plugin's js into IITC `Plugins` directory.

**Comment by Suburbanno** [comment] 2019-06-02 21:35
@johnd0e IITC-MOBILE is not creating the folder.

**Comment by johnd0e** [comment] 2019-06-03 05:34
Have you granted storage permission?

**Comment by Suburbanno** [comment] 2019-06-03 08:45
yah!

**Comment by johnd0e** [comment] 2019-06-03 10:41
> IITC-MOBILE is not creating the folder.

What exactly do you mean?

What do you do?
What is expected behavior?
What is actually observed instead?

**Comment by Suburbanno** [comment] 2019-06-03 15:55
The IITC is not creating the IITC_MOBILE folder, I can not put the files inside the Plugins folder. I gave all the necessary permissions, this happens in both versions, beast and stable.

**Comment by johnd0e** [comment] 2019-06-03 16:03
What if you create it manually?

**Comment by Suburbanno** [comment] 2019-06-03 21:12
I can not add the .js file
![Screenshot_20190603-180945](https://user-images.githubusercontent.com/13632826/58834970-0bba8680-862b-11e9-9861-a160229e2b58.png)

**Comment by Suburbanno** [comment] 2019-06-03 21:13
the application does not let me select the .js file, apparently it gets as "unsupported"

**Comment by coachnyta** [comment] 2019-06-11 20:56
Have you tried renaming the .js file to filename.user.js?

**Comment by Suburbanno** [comment] 2019-06-11 21:20
@coachnyta But it's already like filename.user.js, just look at the photo above.

**Comment by coachnyta** [comment] 2019-06-11 22:01
@Suburbanno ah sorry I thought the file wasn't showing in the screenshot.
Does your file contain any metadata? Taking the missions plugin for example:
```
// ==UserScript==
// @id             iitc-plugin-missions@jonatkins
// @name           IITC plugin: Missions
// @category       Info
// @version        0.1.2.@@DATETIMEVERSION@@
// @description    [@@BUILDNAME@@-@@BUILDDATE@@] View missions. Marking progress on waypoints/missions basis. Showing mission paths on the map.
@@METAINFO@@
// ==/UserScript==
```

**Comment by Suburbanno** [comment] 2019-06-12 12:12
@coachnyta yes
![Screenshot_20190612-091115](https://user-images.githubusercontent.com/13632826/59350308-28715100-8cf2-11e9-9ccb-6a06e2bbf6d1.png)

**Comment by johnd0e** [comment] 2019-06-12 12:24
> I can not add the .js file

What is on attached screenshot?

**Comment by Suburbanno** [comment] 2019-06-12 12:54
@johnd0e this plugin
https://www.giacintogarcea.com/ingress/iitc/minify-some-portal-details-by-zaso.user.js

**Comment by johnd0e** [comment] 2019-06-12 13:16
Yeah, and you told '_the application does not let me select the .js file, apparently it gets as "unsupported"_', but I do not understand what **application** do you mean, as I see it is not iitc interface on screenshot.

**Comment by Suburbanno** [comment] 2019-06-12 13:54
@johnd0e in the IITC configuration, in the plugins part, when clicking add external plugins (+) it opens the native android manager to select the file.

**Comment by johnd0e** [comment] 2019-06-12 14:10
Ok, I understand now.
I do not observe such problem on my phone, perhaps it is depended on system.
The issue need to be investigated further.

And for now you could try some 3rd-party file manager.

**Comment by Suburbanno** [comment] 2019-06-12 14:33
the IITC does not give me the option to choose another file manager, it automatically opens the native manager.

**Comment by johnd0e** [comment] 2019-06-12 16:08
Actually it does:
<details>

![Screenshot_2019-06-12-19-04-13-330_android](https://user-images.githubusercontent.com/1838643/59367758-719ec080-8d45-11e9-8a7c-85521a366532.png)
</details>

**Comment by Suburbanno** [comment] 2019-06-12 16:12
I have other file managers and this option does not appear to me :(

**Comment by johnd0e** [comment] 2019-06-12 16:24
So try Drive or X-plore, for example

**Comment by Suburbanno** [comment] 2019-06-12 16:29
work

**Comment by johnd0e** [comment] 2019-06-12 19:52
I still think that original issue (as it titled) makes sense

Edit: closed in favor of #274

**Comment by johnd0e** [comment] 2019-06-13 05:50
Also I hope that IITC could be fixed to open files with native filemanager too.
More places to check: kml plugin, draw tools import, bookmarks import, etc

**Comment by angel93ayora** [comment] 2019-06-18 14:40
@Suburbanno if the plugin is already on `plugins` folder you dont need to select it from any file manager.

**Comment by aczekajski** [comment] 2019-07-25 19:19
On Android 9 the IITC seems to not register for *.user.js files at all. When I tried the "Open using application" option in files manager, the IITC-Mobile does not appear on the list:
![Screenshot_20190725-211353](https://user-images.githubusercontent.com/3948797/61902219-d42cd400-af21-11e9-8e1f-b06841eccaf9.png)

**Closed as completed** 2019-11-10 15:35 UTC
Labels: enhancement, help wanted, mobile
