### ISSUE TITLE
Link rendering (spherical correction?) is slightly off compared to stock intel. 

### ISSUE THREAD

**Issue by kitor** [IITC-CE/ingress-intel-total-conversion#560] opened 2022-03-04 10:56 UTC
Link between portals: [1] https://intel.ingress.com/?pll=51.146801,16.891397 and [2] https://intel.ingress.com/?pll=51.110173,17.025442
goes "below" portal [3] https://intel.ingress.com/?ll=51.136045,16.928558&z=17 on IITC, but above on stock Intel:

![iitc](https://user-images.githubusercontent.com/643531/156750700-8d574e2c-977e-43dc-802d-c59044bea564.jpg)

![image_2022-03-04_10-22-49](https://user-images.githubusercontent.com/643531/156750725-6c9b8f18-25c1-4894-bb3a-a52569a408fb.png)

This is even more interesting, as on that IITC screenshots there's also a drawn item between [1] and [2] (slightly visible on screenshot) and cross links correctly does not highlight links originating from [3] while, visually those do cross.

**Comment by McBen** [comment] 2022-03-04 11:42
duplicate of #232

**Closed as completed** 2024-05-23 08:56 UTC
